# Generated by Django 3.2.15 on 2022-12-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scienceApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
